### ISSUE TITLE
[feat] atexit hook that calls self.display.terminate() on SIGINT

### ISSUE THREAD

**Issue by Shinyzenith** [Shinyzenith/NextWM#3]

**Comment by Shinyzenith** [comment]
Any progress?

**Comment by actualdankcoder** [comment]
i have no idea what it means

**Comment by Shinyzenith** [comment]
Lmao, what do you not understand? I'll try my best to clarify.

**Comment by actualdankcoder** [comment]
where do you want the hook to go

**Comment by Shinyzenith** [comment]
> where do you want the hook to go

Run on sigint that's all

**Comment by Shinyzenith** [comment]
Or sigterm

**Comment by Shinyzenith** [comment]
only problem that remains, unless I control c in my terminal first and then close the window, the callback isn't run.. Interesting issue.

**Comment by Shinyzenith** [comment]
nvm I fixed it

**Comment by actualdankcoder** [comment]
> only problem that remains, unless I control c in my terminal first and then close the window, the callback isn't run.. Interesting issue.

i was thinking you could run self.display.run() under a thread, that would make it much easier to close on sigint

**Comment by Shinyzenith** [comment]
> > only problem that remains, unless I control c in my terminal first and then close the window, the callback isn't run.. Interesting issue.
> 
> i was thinking you could run self.display.run() under a thread, that would make it much easier to close on sigint

I thought of that too, but then I figured out that I can incorporate the signal checking directly into the wayland event loop (wl_event_loop)

I sent a patch for the same to pywlroots too so in the future others know that this method exists. https://github.com/flacjacket/pywlroots/pull/91
