### ISSUE TITLE
[feat] poetry setup

### ISSUE THREAD

**Issue by actualdankcoder** [Shinyzenith/NextWM#8]
I can make a PR with poetry dependencies setup if you'd like

**Comment by Shinyzenith** [comment]
Hm can we automate testing with poetry? I don't quite like tox

**Comment by actualdankcoder** [comment]
poetry is just an env manager, it will still rely on tox/pytest for testing

**Comment by Shinyzenith** [comment]
> poetry is just an env manager, it will still rely on tox/pytest for testing

If it's like venv then it's kinda useless for a wayland compositor.
